### ISSUE TITLE
cgmanager-0.37 --> no pid file

### ISSUE THREAD

**Issue by udeved** [lxc/cgmanager#11]
I don't get cgmanager started in daemon mode.
cgmanager is used by consolekit2 to track sessions.
/run/cgmanager.pid is missing, yet cgmanager is running.as process.
This strangely only occurs on real hardware, and it somehows works out in vbox.
If I start on real hardware from livecd, cgmanager starts properly with pid, after install, the pid goes missing.

OS: Arch/Manjaro
Kernel: 4.1
init: openrc + eudev
cpu: i3 sandybridge

cgmanager-0.37, I also tried 0.38, same problem.

```
strace -f -o/tmp/strace.cgm.out /usr/bin/cgmanager -m name=systemd --debug > /tmp/cgm.out 2>&1 &
```

http://pastebin.com/Bc8ivfqe

http://pastebin.com/7EPmvTnt

https://github.com/ConsoleKit2/ConsoleKit2/issues/42

**Comment by udeved** [comment]
The error with missing pid file and crashing cgmanager service now also started to appear on my gentoo, which is on the same box.
It used to work, but I guess some package update causes the error.
I currently try to track down what update could be responsible.
Let me know if you need logs or debug.

**Comment by hallyn** [comment]
Hi,

what init system are you using?

The sysvinit script uses start-stop-daemon and expects it to generate a pidfile.

I can confirm that on systemd I don't have a pidfile (but then I don't need one).

**Comment by hallyn** [comment]
Still trying to tell if you actually have a problem.  I notice in the consolekit2 bug you mention that /run/cgmanager/fs has empty subfolders - that is expected, as cgmanager runs in a private mounts namespace.  (That is so that when it exits/crashes the mounts are automatically cleaned up)

does ps -ef | grep cgmanager show anything?

does "cgm getpidcgroupabs $$' and 'cgm listcontrollers' show anything?

**Comment by udeved** [comment]
Hi, thanks for your help.

Init system is on all test boxes openrc, and it uses arch adapted gentoo cgmanager script.
I ma basically the maintainer of the openrc related stuff in manjaro.

I will post the output when I am back at home later tonight.

But I can tell you pretty surely that a cgmanager process is running, upon shutdown, the script successfully terminates the process and its visible in 'ps aux'. It also has a pid assigned, just that the pid file goes into nirvana which makes openrc service crash, yet it shuts down fine.

I confused in the ck bugreport /run/cgmanager/fs with /sys/fs/cgroup/, where cpuacct should contain a nested ck session.

This is output from a manjaro laptop, where the pid file exists. It may be useful as reference.

```
ps -ef | grep cgmanager
root      1522     1  0 19:35 ?        00:00:00 /usr/bin/cgmanager --daemon -m name=systemd
```

http://pastebin.com/RsNQVvYG

```
cgm listcontrollers
bfqio
blkio
cpu
cpuacct
cpuset
devices
freezer
memory
net_cls
name=openrc
name=systemd
```

Output from my manjaro/gentoo box later.

**Comment by hallyn** [comment]
Thanks - so the only problem is the pidfile not being generated?  cgmanager
doesn't do that itself.  Is something provided with openrc which works like
start-stop-daemon --pidfile?

If you'd like to add a config/init/openrc directory to cgmanager upstream,
patch would be gladly accepted

**Comment by udeved** [comment]
Ok, output from my manjaro dev box at home:

```
$ ps -ef | grep cgmanager
root      1253     1  0 22:07 ?        00:00:00 /usr/bin/cgmanager --daemon -m name=systemd
```

```
$ cgm listcontrollers
bfqio
blkio
cpu
cpuacct
cpuset
devices
freezer
memory
net_cls
name=openrc
name=systemd
```

The output of 'cgm getpidcgroupabs $$' is the same as on the laptop.

http://pastebin.com/LhYrYCAZ

```
$ ls /run | grep cgm
cgmanager
```

No pid file.

```
$ rc-status
Runlevel: default
 cgmanager                                                                                             [  crashed  ]
 syslog-ng                                                                                             [  started  ]
 cronie                                                                                                [  started  ]
 dbus                                                                                                  [  started  ]
 consolekit                                                                                            [  started  ]
 netmount                                                                                              [  started  ]
 xdm                                                                                                   [  started  ]
 acpid                                                                                                 [  started  ]
 local                                                                                                 [  started  ]
Dynamic Runlevel: hotplugged
Dynamic Runlevel: needed
 dhcpcd                                                                                                [  started  ]
 xdm-setup                                                                                             [  started  ]
Dynamic Runlevel: manual
```

The initscript for cgmanager:

```
$ cat /etc/init.d/cgmanager
#!/usr/bin/openrc-run
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

DAEMON=/usr/bin/cgmanager
PIDFILE=/run/cgmanager.pid
NESTED=yes
OPTIONS=

depend() {
        after cgproxy
}

start() {
        ebegin "Starting cgmanager server"

        start-stop-daemon --start --pidfile ${PIDFILE} --exec ${DAEMON} \
                -- --daemon -m name=systemd ${OPTIONS}

        eend $?
}

stop() {
        ebegin "Stopping cgmanager server"
        start-stop-daemon --stop --quiet -R TERM/45 -p ${PIDFILE}
        eend $?
}

```

There was a bug on gentoo with version 0.36, which had also the pid file missing.
The solution was temporaily to call start-stop-daemon with '--make-pidfile --background'.
However, if I add this, the service doesn't shutdown properly.
They dropped the extra args with 0.37.

**Comment by udeved** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=552432

**Comment by hallyn** [comment]
> The output of 'cgm getpidcgroupabs $$' is the same as on the laptop.
> 
> http://pastebin.com/LhYrYCAZ

Yeah that should be 'cgm getpidcgroupabs freezer $$'

> The initscript for cgmanager:
> 
> ```
> $ cat /etc/init.d/cgmanager
> #!/usr/bin/openrc-run
> # Copyright 1999-2015 Gentoo Foundation
> # Distributed under the terms of the GNU General Public License v2
> # $Id$
> 
> DAEMON=/usr/bin/cgmanager
> PIDFILE=/run/cgmanager.pid
> NESTED=yes
> OPTIONS=
> 
> depend() {
>         after cgproxy
> }
> 
> start() {
>         ebegin "Starting cgmanager server"
> 
>         start-stop-daemon --start --pidfile ${PIDFILE} --exec ${DAEMON} \
>                 -- --daemon -m name=systemd ${OPTIONS}
> ```

Hm.  So the cgmanager code explicitly does

```
    if (daemonise) {
            nih_main_unlink_pidfile();
    }
```

My mind's a bit fried right now from other bugs;  I can't decide
whether this is a bug in cgmanager's syvinit script, or whether
it shouldn't unlink it's pidfile above.

Does it solve your problem if you change start() to:

```
     start-stop-daemon --background --start --pidfile ${PIDFILE} --exec ${DAEMON} \
             -- -m name=systemd ${OPTIONS}
```

(In other words tell start-stop-daemon to do the backgrounding
instead of cgmanager)

The warning in the manpage makes me think it's a bad idea, but I'd like
to know whether it works...

**Comment by udeved** [comment]
I will test this.
What I don't understand, why does it work on some machine, livecd and vbox?
Could it be some kind of race condition where the dbus socket is not ready?
I already experimented with libnih, incorporating a gentoo threading patch, but it didn't make a difference.

For example I get this logged with consolekit:

```
localhost console-kit-daemon[1337]: WARNING: Failed to get the session id from cgmanager, the error was: Connection is closed
```

```
$ cgm getpidcgroupabs freezer $$
/
```

**Comment by hallyn** [comment]
Yeah that would fix it.

But I think I will post a patch to not have cgmanager remove its pidfile.

**Comment by hallyn** [comment]
On Tue, Sep 01, 2015 at 01:48:24PM -0700, udeved wrote:

> I will test this.
> What I don't understand, why does it work on some machine, livecd and vbox?

Any chance they are using

https://552432.bugs.gentoo.org/attachment.cgi?id=405310

?

**Comment by udeved** [comment]
Nope, I do the packages for manjaro repo, they basically all have the same setup in terms of packages.

**Comment by udeved** [comment]
```
Does it solve your problem if you change start() to:
…

start-stop-daemon --background --start --pidfile ${PIDFILE} --exec ${DAEMON} \
                 -- -m name=systemd ${OPTIONS}

(In other words tell start-stop-daemon to do the backgrounding
instead of cgmanager)

The warning in the manpage makes me think it's a bad idea, but I'd like
to know whether it works...

```

```
$ ps -ef | grep cgmanager
root      1260     1  0 23:13 ?        00:00:00 /usr/bin/cgmanager --daemon -m name=systemd
```

No, it doesn't.

```
rc-status
Runlevel: default
 cgmanager                                                                       [  crashed  ]
```

```
$ ls /run | grep cgm
cgmanager
```
