### ISSUE TITLE
Dependency on pam

### ISSUE THREAD

**Issue by cwilling** [lxc/cgmanager#13]
The last two cgmanager releases (0.38, 0.39) fail configuration if pam is not found, which is the case for (at least) Slackware. I am able to remove the pam related stuff from configure.ac & Makefile.am, after which bootstrap.sh/configure/make all works as before. However I'm unsure whether this is safe - I'd feel better if there were a --without-pam configuraion option, or even allowing --with-pamdir=none. Is this possible please?
Thanks,
chris

**Comment by stgraber** [comment]
Sounds reasonable to me, basically making libpam-cgm to depend on libpam-dev being present.

**Comment by hallyn** [comment]
@cwilling if you have a patch (sounds like you do) please feel free to sign-off and submit through a PR or mailing list.

**Comment by cwilling** [comment]
I'm no autotools star but the pull request #14 has changes which work for me on -current Slackware. Also tested on Ubuntu 15.04 for the normal case where --with-pamdir wouldn't be specified.

**Comment by hallyn** [comment]
Note if you put "Closes #13" this would have been auto-closed :)

Thanks for the fix!
