### ISSUE TITLE
unified cgroup hierarchy

### ISSUE THREAD

**Issue by brauner** [lxc/cgmanager#18]
I tried to run `lxcfs v0.10` and `cgmanager v0.39` with the unified cgroup hierarchy with `systemd 226` by passing `systemd.unified_cgroup_hierarchy=1`  to `systemd`. This doesn't seem to work. The assertions in `cgmanager.c`: `nih_assert(server != NULL);` fails. This might have something to do with how `systemd 226` starts the `dbus` session but I am not sure:

> "systemd now supports the concept of user buses replacing
>           session buses, if used with dbus-1.10 (and enabled via dbus
>           --enable-user-session). It previously only supported this on
>           kdbus-enabled systems, and this release expands this to
>           'dbus-daemon' systems." (http://lists.freedesktop.org/archives/systemd-devel/2015-September/034177.html)

**Comment by hallyn** [comment]
Note that while cgmanager is unified-aware, lxcfs is not yet.

The cgmanager unified support actually means that non-unified-aware aplicaations can use cgmanager as normal, and cgmanager emulates the non-unified api on unified cgfs (by faking .cgm_leaf etc).

I figured the next step for cgmanager would be to work on a new, more abstracted, v2 API (which ignores legacy.vs.unified).  This API would not be as tied to the current filenames.  The current systemd api may be a decent starting point.

**Comment by hallyn** [comment]
Just to be sure - you're saying talking about just on the host, not in a container?  cgmanager refuses to start?

**Comment by brauner** [comment]
Yes, `cgmanager` fails to start on the host. I haven't tried to start it in a container.

**Comment by brauner** [comment]
Note that this is on an `Archlinux` host which means that the `systemd` that runs on the host is unpatched i.e. identical to pulling from the corresponding upstream tag (`226`). I thought I mention this in case it matters. The kernel version is `4.2.1`.

**Comment by brauner** [comment]
`cgmanager` is deprecated.
