### ISSUE TITLE
cgmanager on centos7

### ISSUE THREAD

**Issue by ameyaGit** [lxc/cgmanager#21]
Cgmanager on centos 7 doesn't work . Has anyone tried compiling it ?

**Comment by ameyaGit** [comment]
I need it urgently on centos 7 . Anyone tried compiling it ?

**Comment by ameyaGit** [comment]
Hi,
    I compiled it successfully on centos 7, however this is the output 

/etc/init.d/cgmanager: line 36: /lib/init/vars.sh: No such file or directory

**Comment by hallyn** [comment]
On Thu, Nov 05, 2015 at 10:33:36PM -0800, ameyaGit wrote:

> Hi,
>     I compiled it successfully on centos 7, however this is the output 
> 
> /etc/init.d/cgmanager: line 36: /lib/init/vars.sh: No such file or directory

# Load the VERBOSE setting and other rcS variables

. /lib/init/vars.sh

Some googling suggests you should be able to just ignore that.  So perhaps
this should be changed to

[ -f /lib/init/vars.sh ] && . /lib/init/vars.sh

**Comment by ameyaGit** [comment]
Hi,
    I will try this and let you know. You please try as well . I can post the output of configure too . Thank you for the response .

**Comment by ameyaGit** [comment]
Here is the output

./configure --prefix=/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define EXTENSIONS... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-li nux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format. .. func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libr aries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for nih-dbus-tool... /usr/local/bin/nih-dbus-tool
checking for setns... yes
checking for pivot_root... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for NIH... yes
checking for NIH_DBUS... yes
checking for DBUS... yes
checking host distribution... checking for /etc/redhat-release... yes
checking for /etc/oracle-release... no
checking for /etc/centos-release... yes
checking for /etc/fedora-release... no
checking for /etc/SuSE-release... no
checking for /etc/gentoo-release... no
checking for /etc/debian_version... no
checking for /etc/arch-release... no
checking for /etc/slackware-version... no
checking for /etc/frugalware-release... no
checking for /etc/mandrakelinux-release... no
checking for /etc/mandriva-release... no
checking for /etc/pardus-release... no
centos
checking for init system type... sysvinit
checking for help2man... false // No help2man //
checking for pam_authenticate in -lpam... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config/Makefile
config.status: creating config/init/Makefile
config.status: creating config/init/bsd/Makefile
config.status: creating config/init/systemd/Makefile
config.status: creating config/init/sysvinit/Makefile
config.status: creating config/init/upstart/Makefile
config.status: creating config/init/upstart/sessions/Makefile
config.status: creating libcgmanager.pc.in
config.status: creating cgmanager.spec
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by hallyn** [comment]
On Mon, Nov 09, 2015 at 02:40:30AM -0800, ameyaGit wrote:

> Here is the output
> checking for help2man... false // No help2man //

ok, you might want help2man installed, but it looks like that suceeded

what happens when you proceed to 'make' ?

**Comment by ameyaGit** [comment]
make
/usr/local/bin/nih-dbus-tool \
--package=cgmanager \
--mode=object \
--prefix=cgmanager \
--default-interface=org.linuxcontainers.cgmanager0_0 \
org.linuxcontainers.cgmanager.xml
/usr/local/bin/nih-dbus-tool \
--package=cgmanager \
--mode=proxy --prefix=cgmanager \
--default-interface=org.linuxcontainers.cgmanager0_0 \
--output=cgmanager-client.c \
org.linuxcontainers.cgmanager.xml
make  all-recursive
make[1]: Entering directory `/root/cgmanager'
Making all in config
make[2]: Entering directory`/root/cgmanager/config'
Making all in init
make[3]: Entering directory `/root/cgmanager/config/init'
Making all in bsd
make[4]: Entering directory`/root/cgmanager/config/init/bsd'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory`/root/cgmanager/config/init/bsd'
Making all in systemd
make[4]: Entering directory `/root/cgmanager/config/init/systemd'
make[4]: Nothing to be done for`all'.
make[4]: Leaving directory `/root/cgmanager/config/init/systemd'
Making all in sysvinit
make[4]: Entering directory`/root/cgmanager/config/init/sysvinit'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory`/root/cgmanager/config/init/sysvinit'
Making all in upstart
make[4]: Entering directory `/root/cgmanager/config/init/upstart'
Making all in sessions
make[5]: Entering directory`/root/cgmanager/config/init/upstart/sessions'
make[5]: Nothing to be done for `all'.
make[5]: Leaving directory`/root/cgmanager/config/init/upstart/sessions'
make[5]: Entering directory `/root/cgmanager/config/init/upstart'
make[5]: Nothing to be done for`all-am'.
make[5]: Leaving directory `/root/cgmanager/config/init/upstart'
make[4]: Leaving directory`/root/cgmanager/config/init/upstart'
make[4]: Entering directory `/root/cgmanager/config/init'
make[4]: Nothing to be done for`all-am'.
make[4]: Leaving directory `/root/cgmanager/config/init'
make[3]: Leaving directory`/root/cgmanager/config/init'
make[3]: Entering directory `/root/cgmanager/config'
make[3]: Nothing to be done for`all-am'.
make[3]: Leaving directory `/root/cgmanager/config'
make[2]: Leaving directory`/root/cgmanager/config'
make[2]: Entering directory `/root/cgmanager'
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -fPIC -DPIC -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -g -O2 -MT libcgmanager_la-cgmanager-client.lo -MD -MP -MF .deps/libcgmanager_la-cgmanager-client.Tpo -c -o libcgmanager_la-cgmanager-client.lo`test -f 'cgmanager-client.c' || echo './'`cgmanager-client.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -fPIC -DPIC -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -g -O2 -MT libcgmanager_la-cgmanager-client.lo -MD -MP -MF .deps/libcgmanager_la-cgmanager-client.Tpo -c cgmanager-client.c  -fPIC -DPIC -o .libs/libcgmanager_la-cgmanager-client.o
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -fPIC -DPIC -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -g -O2 -MT libcgmanager_la-cgmanager-client.lo -MD -MP -MF .deps/libcgmanager_la-cgmanager-client.Tpo -c cgmanager-client.c -o libcgmanager_la-cgmanager-client.o >/dev/null 2>&1
mv -f .deps/libcgmanager_la-cgmanager-client.Tpo .deps/libcgmanager_la-cgmanager-client.Plo
/bin/sh ./libtool  --tag=CC   --mode=link gcc -std=gnu99 -fPIC -DPIC -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -g -O2 -E -version-info 0:0:0  -o libcgmanager.la -rpath //lib libcgmanager_la-cgmanager-client.lo -L/usr/local/lib -ldbus-1   -L/usr/local/lib -lnih   -L/usr/local/lib -lnih-dbus
libtool: link: gcc -shared  -fPIC -DPIC  .libs/libcgmanager_la-cgmanager-client.o   -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -L/usr/local/lib /usr/local/lib/libnih-dbus.so /usr/local/lib/libnih.so /usr/local/lib/libdbus-1.so -lpthread -lrt  -O2   -Wl,-soname -Wl,libcgmanager.so.0 -o .libs/libcgmanager.so.0.0.0
libtool: link: (cd ".libs" && rm -f "libcgmanager.so.0" && ln -s "libcgmanager.so.0.0.0" "libcgmanager.so.0")
libtool: link: (cd ".libs" && rm -f "libcgmanager.so" && ln -s "libcgmanager.so.0.0.0" "libcgmanager.so")
libtool: link: ar cru .libs/libcgmanager.a  libcgmanager_la-cgmanager-client.o
libtool: link: ranlib .libs/libcgmanager.a
libtool: link: ( cd ".libs" && rm -f "libcgmanager.la" && ln -s "../libcgmanager.la" "libcgmanager.la" )
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -MT pam/pam_cgm_la-pam_cgm.lo -MD -MP -MF pam/.deps/pam_cgm_la-pam_cgm.Tpo -c -o pam/pam_cgm_la-pam_cgm.lo`test -f 'pam/pam_cgm.c' || echo './'`pam/pam_cgm.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -DLIBEXECDIR=\"//libexec\" -g -O2 -MT pam/pam_cgm_la-pam_cgm.lo -MD -MP -MF pam/.deps/pam_cgm_la-pam_cgm.Tpo -c pam/pam_cgm.c  -fPIC -DPIC -o pam/.libs/pam_cgm_la-pam_cgm.o
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -DLIBEXECDIR=\"//libexec\" -g -O2 -MT pam/pam_cgm_la-pam_cgm.lo -MD -MP -MF pam/.deps/pam_cgm_la-pam_cgm.Tpo -c pam/pam_cgm.c -o pam/pam_cgm_la-pam_cgm.o >/dev/null 2>&1
mv -f pam/.deps/pam_cgm_la-pam_cgm.Tpo pam/.deps/pam_cgm_la-pam_cgm.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -MT pam/pam_cgm_la-cgmanager.lo -MD -MP -MF pam/.deps/pam_cgm_la-cgmanager.Tpo -c -o pam/pam_cgm_la-cgmanager.lo`test -f 'pam/cgmanager.c' || echo './'`pam/cgmanager.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -DLIBEXECDIR=\"//libexec\" -g -O2 -MT pam/pam_cgm_la-cgmanager.lo -MD -MP -MF pam/.deps/pam_cgm_la-cgmanager.Tpo -c pam/cgmanager.c  -fPIC -DPIC -o pam/.libs/pam_cgm_la-cgmanager.o
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -DLIBEXECDIR=\"//libexec\" -g -O2 -MT pam/pam_cgm_la-cgmanager.lo -MD -MP -MF pam/.deps/pam_cgm_la-cgmanager.Tpo -c pam/cgmanager.c -o pam/pam_cgm_la-cgmanager.o >/dev/null 2>&1
mv -f pam/.deps/pam_cgm_la-cgmanager.Tpo pam/.deps/pam_cgm_la-cgmanager.Plo
/bin/sh ./libtool  --tag=CC   --mode=link gcc -std=gnu99 -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -L/usr/local/lib -ldbus-1   -L/usr/local/lib -lnih   -L/usr/local/lib -lnih-dbus   -module -avoid-version -shared  -o pam_cgm.la -rpath //lib/security pam/pam_cgm_la-pam_cgm.lo pam/pam_cgm_la-cgmanager.lo  -lpam -L. -lcgmanager
libtool: link: gcc -shared  -fPIC -DPIC  pam/.libs/pam_cgm_la-pam_cgm.o pam/.libs/pam_cgm_la-cgmanager.o   -Wl,-rpath -Wl,/root/cgmanager/.libs -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,//lib -Wl,-rpath -Wl,/usr/local/lib -L/usr/local/lib -lpam -L. /root/cgmanager/.libs/libcgmanager.so /usr/local/lib/libnih-dbus.so /usr/local/lib/libnih.so /usr/local/lib/libdbus-1.so -lpthread -lrt  -O2   -Wl,-soname -Wl,pam_cgm.so -o .libs/pam_cgm.so
libtool: link: ( cd ".libs" && rm -f "pam_cgm.la" && ln -s "../pam_cgm.la" "pam_cgm.la" )
depbase=`echo cgm.o | sed 's|[^/]_$|.deps/&|;s|.o$||'`;\
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -MT cgm.o -MD -MP -MF $depbase.Tpo -c -o cgm.o cgm.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc -std=gnu99 -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -L/usr/local/lib -ldbus-1   -L/usr/local/lib -lnih   -L/usr/local/lib -lnih-dbus    -o cgm cgm.o -L.libs -lcgmanager
libtool: link: gcc -std=gnu99 -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -DLIBEXECDIR=\"//libexec\" -g -O2 -o .libs/cgm cgm.o  -L/usr/local/lib -L.libs /root/cgmanager/.libs/libcgmanager.so /usr/local/lib/libnih-dbus.so /usr/local/lib/libnih.so /usr/local/lib/libdbus-1.so -lpthread -lrt -Wl,-rpath -Wl,//lib -Wl,-rpath -Wl,/usr/local/lib
depbase=`echo cgm-release-agent.o | sed 's|[^/]_$|.deps/&|;s|.o$||'`;\
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -MT cgm-release-agent.o -MD -MP -MF $depbase.Tpo -c -o cgm-release-agent.o cgm-release-agent.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc -std=gnu99 -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -L/usr/local/lib -ldbus-1   -L/usr/local/lib -lnih   -L/usr/local/lib -lnih-dbus    -o cgm-release-agent cgm-release-agent.o -L.libs -lcgmanager
libtool: link: gcc -std=gnu99 -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -DLIBEXECDIR=\"//libexec\" -g -O2 -o .libs/cgm-release-agent cgm-release-agent.o  -L/usr/local/lib -L.libs /root/cgmanager/.libs/libcgmanager.so /usr/local/lib/libnih-dbus.so /usr/local/lib/libnih.so /usr/local/lib/libdbus-1.so -lpthread -lrt -Wl,-rpath -Wl,//lib -Wl,-rpath -Wl,/usr/local/lib
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -DCGMANAGER -g -O2 -MT cgmanager-cgmanager.o -MD -MP -MF .deps/cgmanager-cgmanager.Tpo -c -o cgmanager-cgmanager.o`test -f 'cgmanager.c' || echo './'`cgmanager.c
mv -f .deps/cgmanager-cgmanager.Tpo .deps/cgmanager-cgmanager.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -DCGMANAGER -g -O2 -MT cgmanager-org.linuxcontainers.cgmanager.o -MD -MP -MF .deps/cgmanager-org.linuxcontainers.cgmanager.Tpo -c -o cgmanager-org.linuxcontainers.cgmanager.o`test -f 'org.linuxcontainers.cgmanager.c' || echo './'`org.linuxcontainers.cgmanager.c
mv -f .deps/cgmanager-org.linuxcontainers.cgmanager.Tpo .deps/cgmanager-org.linuxcontainers.cgmanager.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -DCGMANAGER -g -O2 -MT cgmanager-access_checks.o -MD -MP -MF .deps/cgmanager-access_checks.Tpo -c -o cgmanager-access_checks.o`test -f 'access_checks.c' || echo './'`access_checks.c
mv -f .deps/cgmanager-access_checks.Tpo .deps/cgmanager-access_checks.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -DCGMANAGER -g -O2 -MT cgmanager-fs.o -MD -MP -MF .deps/cgmanager-fs.Tpo -c -o cgmanager-fs.o`test -f 'fs.c' || echo './'`fs.c
fs.c: In function âcompute_proxy_cgroupâ:
fs.c:1705:8: warning: unused variable âpointâ [-Wunused-variable]
  char *point;
        ^
mv -f .deps/cgmanager-fs.Tpo .deps/cgmanager-fs.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -DCGMANAGER -g -O2 -MT cgmanager-frontend.o -MD -MP -MF .deps/cgmanager-frontend.Tpo -c -o cgmanager-frontend.o`test -f 'frontend.c' || echo './'`frontend.c
mv -f .deps/cgmanager-frontend.Tpo .deps/cgmanager-frontend.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc -std=gnu99 -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -DCGMANAGER -g -O2 -L/usr/local/lib -ldbus-1   -L/usr/local/lib -lnih   -L/usr/local/lib -lnih-dbus    -o cgmanager cgmanager-cgmanager.o cgmanager-org.linuxcontainers.cgmanager.o cgmanager-access_checks.o cgmanager-fs.o cgmanager-frontend.o
libtool: link: gcc -std=gnu99 -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -DLIBEXECDIR=\"//libexec\" -DCGMANAGER -g -O2 -o cgmanager cgmanager-cgmanager.o cgmanager-org.linuxcontainers.cgmanager.o cgmanager-access_checks.o cgmanager-fs.o cgmanager-frontend.o  -L/usr/local/lib /usr/local/lib/libnih-dbus.so /usr/local/lib/libnih.so /usr/local/lib/libdbus-1.so -lpthread -lrt -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib
depbase=`echo cgmanager-proxy.o | sed 's|[^/]_$|.deps/&|;s|.o$||'`;\
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -MT cgmanager-proxy.o -MD -MP -MF $depbase.Tpo -c -o cgmanager-proxy.o cgmanager-proxy.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo org.linuxcontainers.cgmanager.o | sed 's|[^/]_$|.deps/&|;s|.o$||'`;\
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -MT org.linuxcontainers.cgmanager.o -MD -MP -MF $depbase.Tpo -c -o org.linuxcontainers.cgmanager.o org.linuxcontainers.cgmanager.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo access_checks.o | sed 's|[^/]_$|.deps/&|;s|.o$||'`;\
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -MT access_checks.o -MD -MP -MF $depbase.Tpo -c -o access_checks.o access_checks.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo fs.o | sed 's|[^/]_$|.deps/&|;s|.o$||'`;\
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -MT fs.o -MD -MP -MF $depbase.Tpo -c -o fs.o fs.c &&\
mv -f $depbase.Tpo $depbase.Po
fs.c: In function âcompute_proxy_cgroupâ:
fs.c:1705:8: warning: unused variable âpointâ [-Wunused-variable]
  char *point;
        ^
depbase=`echo frontend.o | sed 's|[^/]*$|.deps/&|;s|.o$||'`;\
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -MT frontend.o -MD -MP -MF $depbase.Tpo -c -o frontend.o frontend.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc -std=gnu99 -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include   -I/usr/local/include   -I/usr/local/include   -DLIBEXECDIR=\"//libexec\" -g -O2 -L/usr/local/lib -ldbus-1   -L/usr/local/lib -lnih   -L/usr/local/lib -lnih-dbus    -o cgproxy cgmanager-proxy.o org.linuxcontainers.cgmanager.o access_checks.o fs.o frontend.o
libtool: link: gcc -std=gnu99 -Wall -ggdb -D_GNU_SOURCE -DSBINDIR=\"//sbin\" -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include -I/usr/local/include -DLIBEXECDIR=\"//libexec\" -g -O2 -o cgproxy cgmanager-proxy.o org.linuxcontainers.cgmanager.o access_checks.o fs.o frontend.o  -L/usr/local/lib /usr/local/lib/libnih-dbus.so /usr/local/lib/libnih.so /usr/local/lib/libdbus-1.so -lpthread -lrt -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib
sed -e 's|[@]LIBCGMANAGER_VERSION_DOTTED[@]|0.0.0|g' \
        libcgmanager.pc.in > libcgmanager.pc
make[2]: Leaving directory`/root/cgmanager'
make[1]: Leaving directory `/root/cgmanager'

**Comment by ameyaGit** [comment]
Hi,
Cgmanager is not required for LXCFS 0.18 or LXCFS 2.0.0.beta1 ?

**Comment by hallyn** [comment]
No
