### ISSUE TITLE
Boot time configuration

### ISSUE THREAD

**Issue by hallyn** [lxc/cgmanager#3]
People really want a libcgroup-style boot time configuration.  Come up with a configuration file format and implement the setup-at-startup.

**Comment by peletiah** [comment]
Has any progress been made in this? Do you think this might be available in the near future?

**Comment by hallyn** [comment]
@peletiah 

what exactly would you want to use it for?

I'm trying to decide whether we should simply say "systemd should do it", or whether we should have a uos (summit.ubuntu.com) session on whether/how to split.

**Comment by peletiah** [comment]
I'm running unprivileged containers on a Debian Jessie, where I have to manually set cgroup-permissions to start them  (Respectively with a ugly custom boot-script). It would be neat if there was a built-in-option to do this.

**Comment by hallyn** [comment]
Have you tried the libpam-cgm module that now ships with cgmanager?

**Comment by peletiah** [comment]
No, it's not available in vanilla Jessie. But then again I'm out of luck with any update you release anyway, as they will not find their way into Jessie :-) Probably permissions will work better in Stretch by default, as they already do in Ubuntu.
