### ISSUE TITLE
cgmanager fails to start after recent update

### ISSUE THREAD

**Issue by haasn** [lxc/cgmanager#32]
```
Nov 19 00:49:43 xor systemd[1]: Started Cgroup management daemon.
Nov 19 00:49:43 xor cgmanager[9666]: cgmanager: Error mounting unified: No such file or directory
Nov 19 00:49:43 xor cgmanager[9666]: cgmanager: failed to collect cgroup subsystems
Nov 19 00:49:43 xor systemd[1]: cgmanager.service: Main process exited, code=exited, status=1/FAILURE
Nov 19 00:49:43 xor systemd[1]: cgmanager.service: Unit entered failed state.
Nov 19 00:49:43 xor systemd[1]: cgmanager.service: Failed with result 'exit-code'.
Nov 19 00:49:43 xor systemd[1]: cgmanager.service: Service hold-off time over, scheduling restart.
Nov 19 00:49:43 xor systemd[1]: Stopped Cgroup management daemon.
```

Not really sure what this is about. I'm on kernel 4.8.8 and systemd ver 232 (if that's relevant)

**Comment by hallyn** [comment]
This is because systemd 232 mounts name=systemd as the new unified
hierarchy, which cgmanager does not support.  cgmanager 233 and 231
should be fine.

**Comment by hallyn** [comment]
(Sorry, supporting that is not in scope for cgmanager, as it has been deprecated)

**Comment by karimodm** [comment]
@hallyn I am sorry but I didn't get your answer. How can I make cgmanager start under systemd 233? It now refuses to start with the error mentioned.

**Comment by hallyn** [comment]
If you are running systemd you should not need cgmanager.  Can you tell us why you need it running?

**Comment by karimodm** [comment]
Due to a recent upgrade I am having issues running LXC containers, and I though it was due to cgmanager failing to mount certain cgroups, but I realized it is actually not the case. It is an issue with cgrulesengd.
