### ISSUE TITLE
cgmanager: Error mounting unified: No such file or directory on openrc.

### ISSUE THREAD

**Issue by Pekkari** [lxc/cgmanager#34]
Hi,

Upgrading to cgmanager 0.41 rendered in breaking openrc systems that use unprivileged lxcs. I build upstream code using --with-init-script=openrc, and I execute the command line like:

`# ./cgmanager -m name=systemd
cgmanager: Error mounting unified: No such file or directory

cgmanager: failed to collect cgroup subsystems`

Dropping the systemd piece doesn't yield any difference:

`# ./cgmanager
cgmanager: Error mounting unified: No such file or directory

cgmanager: failed to collect cgroup subsystems`

Thanks!

**Comment by stgraber** [comment]
You're running on a system that's got a cgroupv2 unified hierarchy mounted. This isn't supported by cgmanager as cgmanager was deprecated before cgroupv2 got merged in the upstream kernel.

**Comment by Pekkari** [comment]
I see, Thanks Stephane.
