### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by maciejsszmigiero** [lxc/cgmanager#39]
Last version (0.41) was released more than 3 years ago.

Since then cgmanager gained important fixes, related to
compatibility with 4.5+ kernels and performing operations on cgroups v2.
Some new functionality was also added since, for example PAM_CGM
module was made much more configurable.

Due to the above, it would be good to make a new cgmanager release.

**Comment by stgraber** [comment]
@hallyn deferring that one to you, if you're happy with it, let me know if you want to tag and release yourself or if I should do it.

Not planning on doing a full release announcement or anything bug tag and tarball would be fine with me.

**Comment by hallyn** [comment]
Thanks @stgraber, sounds good.  I don't relisth the thought of a sudden onslought of bug reports on an abandoned project, but a final release sounds.

**Comment by stgraber** [comment]
@hallyn yeah, that's why I don't intend to announce it, just make the tarball, publish it on the site and tag on github.

**Comment by stgraber** [comment]
Done, tagged and tarballs are available on website.

**Comment by hallyn** [comment]
Thanks!

**Comment by maciejsszmigiero** [comment]
Thanks, too!
